---
title: "Bayesian Lasso"
author: "Michal Malyska, Alin Morariu, Shawn Unger"
output: pdf_document
---

\null \newpage
\tableofcontents
\null \newpage


```{r Setup and Library Load, message=FALSE, warning=FALSE}
library(tidyverse) # obvious reasons
library(rstan) # same
library(tidyposterior) # visuals for bayesian
library(tidybayes) # same 
library(bayesplot) # same
library(coda) # bayesian diagnostics
library(here) # working on the project together
set.seed(314159) # For Pi-Day
```

# Data Generating Function

```{r Data Generator}
Generate_Dataset_BL <- function(num_predictors, num_noise, dataset_size, distribution = "Normal") {
	# Generates a dataset of length dataset_size from num_predictors predictors sampled
	# from one of the specified distributions with preset params. Adds num_noise of 
	# redundant dimensions to data. Returns a dataset, betas.
	
	### Generate the Betas:
	if (distribution == "Normal") {
		betas <- rnorm(num_predictors)
	}
	else if (distribution == "Exponential") {
		betas <- rexp(num_predictors)
	}
	else if (distribution == "t") {
		betas <- rt(num_predictors, 2)
	}
	else if (distribution == "Cauchy") {
		betas <- rcauchy(num_predictors)
	}
	else if (distribution == "Uniform") {
		betas <- runif(num_predictors)
	}
	else {
		stop("Invalid Distribution")
	}
	
	### Generate the sample x's 
	
	# Total number of real x's to sample
	num_real_x <- num_predictors * dataset_size
	real_x <- rnorm(num_real_x)
	
	# Convert to a matrix and then save as a tibble:
	real_x_mat <- matrix(real_x, ncol = num_predictors)
	
	# Compute real y's
	real_y <- real_x_mat %*% betas
	noisy_y <- real_y + rnorm(dataset_size, sd = 0.1)
	
	# Sample Noise x's 
	num_noise_x <- num_noise * dataset_size
	noise_x <- rnorm(num_noise_x)
	noise_x_mat <- matrix(noise_x, ncol = num_noise)
	
	# Combine into data:
	real_x_df <- as_tibble(real_x_mat)
	noise_x_df <- as_tibble(noise_x_mat)
	noisy_y_df <- as_tibble(noisy_y)
	combined_x <- bind_cols(real_x_df, noise_x_df)
	names(combined_x) <- paste0('x', 1:(ncol(combined_x)))
	
	
	# Return
	return(list(combined_x, noisy_y_df, betas))
}
```


```{r Lasso 1 Trial - fit1}
# Generate a simple dataset of size (5,10,1000)
N = 1000

dataset1 <- Generate_Dataset_BL(5,10,N)
x1 <- dataset1[[1]]
y1 <- dataset1[[2]]$V1
betas1 <- dataset1[[3]]

# Create data list for stan:
dat1 <- list(N = N, K = ncol(x1), y = y1, X = x1)

# Fit Stan model:
fit1 <- stan(file = "Lasso1.stan",
			 data = list(
			 	N = N,
			 	K = 15,
			 	y = y1,
			 	X = x1
			 ))


```

```{r Evaluate fit1}
check_hmc_diagnostics(fit1)
```


```{r Lasso 2 Trial - fit2 }
# Generate a simple dataset of size (5,100,1000)
N = 1000

dataset2 <- Generate_Dataset_BL(5,100,N)
x2 <- dataset2[[1]]
y2 <- dataset2[[2]]$V1
betas2 <- dataset2[[3]]

# Fit Stan model:
fit2 <- stan(file = "Lasso1.stan",
			 data = list(N = N,
			 			K = ncol(x2),
			 			y = y2,
			 			X = x2),
			 chains = 5,
			 iter = 10000,
			 warmup = 2000,
			 thin = 10)
```

```{r Evaluate fit2}
check_hmc_diagnostics(fit2)

posterior2 <- extract(fit2, inc_warmup = TRUE, permuted = FALSE)

color_scheme_set("red")
betas <- paste0('beta[', 1:105,']')

mcmc_areas(posterior2,
           pars = betas,
           prob = 0.8)
print(fit2)
```


```{r, eval = T, echo= F}
load("results_list.Rdata")

res <- read_csv("Results Summary.csv")

library(ggplot2)
sift <- res %>% filter(squared_deviation >= mean(res$squared_deviation))
sift
ggplot(res, aes(x = d, y = epsilon_droot_m, color = m )) + geom_point()
install.packages("ggpubr")
library(ggpubr)
mean(res$squared_deviation)
mean(res$max_normed_deviation)

res$epsilon_dlinear_halfd

colnames(res)

x_l <-   xlab("Log Dimensions")

#plot 1
plot_epsilon_droot_m <- ggplot(res, aes(x = log(d), y = epsilon_droot_m, color = m )) + geom_point() +  x_l + ylab("root m e") + expand_limits(y = 0)

#plot 2
plot_epsilon_droot_rootd <- ggplot(res, aes(x = log(d), y = epsilon_droot_rootd, color = m )) + geom_point() +  x_l + ylab("root root e")

#plot 3
plot_epsilon_droot_halfd <- ggplot(res, aes(x = log(d), y = epsilon_droot_halfd, color = m )) + geom_point() +  x_l + ylab("root halfed e") + expand_limits(y = 0)

#plot 4
plot_epsilon_dlinear_m <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_m, color = m )) + geom_point() +  x_l + ylab("Linear m e")

#plot 5
plot_epsilon_dlinear_rootd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_rootd, color = m )) + geom_point() +  x_l + ylab("Linear root e")

#plot 6
plot_epsilon_dlinear_halfd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_halfd, color = m )) + geom_point() +  x_l + ylab("Linear halfed e")

ggarrange(plot_epsilon_droot_m, plot_epsilon_droot_rootd, plot_epsilon_droot_halfd , plot_epsilon_dlinear_m, plot_epsilon_dlinear_rootd, plot_epsilon_dlinear_halfd,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 2)


```



```{r, echo = F, eval = T}

x_l <-   xlab("Log Dimensions")

res$"m/k" <- res$m/res$k

#plot 1
plot_epsilon_droot_m <- ggplot(res, aes(x = log(d), y = epsilon_droot_m, color = m/k )) + geom_point() +  x_l + ylab("root m epsilon") + expand_limits(y = 0)

#plot 2
plot_epsilon_droot_rootd <- ggplot(res, aes(x = log(d), y = epsilon_droot_rootd, color = m/k )) + geom_point() +  x_l + ylab("root root epsilon")

#plot 3
plot_epsilon_droot_halfd <- ggplot(res, aes(x = log(d), y = epsilon_droot_halfd, color = m/k )) + geom_point() +  x_l + ylab("root halfed epsilon") + expand_limits(y = 0)

#plot 4
plot_epsilon_dlinear_m <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_m, color = m/k )) + geom_point() +  x_l + ylab("Linear m epsilon") 

#plot 5
plot_epsilon_dlinear_rootd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_rootd, color = m/k )) + geom_point() +  x_l + ylab("Linear root epsilon")

#plot 6
plot_epsilon_dlinear_halfd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_halfd, color = m/k )) + geom_point() +  x_l + ylab("Linear halfed epsilon")

ggarrange(plot_epsilon_droot_m, plot_epsilon_droot_rootd, plot_epsilon_droot_halfd , plot_epsilon_dlinear_m, plot_epsilon_dlinear_rootd, plot_epsilon_dlinear_halfd,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 2)
```

```{r, echo = F, eval = T}

#plot 1
plot_epsilon_droot_m <- ggplot(res, aes(x = log(d), y = epsilon_droot_m, color = log(m/k) )) + geom_point() +  x_l + ylab("root m epsilon") + expand_limits(y = 0)

#plot 2
plot_epsilon_droot_rootd <- ggplot(res, aes(x = log(d), y = epsilon_droot_rootd, color = log(m/k) )) + geom_point() +  x_l + ylab("root root epsilon") 

#plot 3
plot_epsilon_droot_halfd <- ggplot(res, aes(x = log(d), y = epsilon_droot_halfd, color = log(m/k) )) + geom_point() +  x_l + ylab("root halfed epsilon") + expand_limits(y = 0)

#plot 4
plot_epsilon_dlinear_m <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_m, color = log(m/k) )) + geom_point() +  x_l + ylab("Linear m epsilon") + scale_y_continuous(limits = c(0,150))

#plot 5
plot_epsilon_dlinear_rootd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_rootd, color = log(m/k) )) + geom_point() +  x_l + ylab("Linear root epsilon")+ scale_y_continuous(limits = c(0,150))

#plot 6
plot_epsilon_dlinear_halfd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_halfd, color = log(m/k))) + geom_point() +  x_l + ylab("Linear halfed epsilon")+ scale_y_continuous(limits = c(0,150))

ggarrange(plot_epsilon_droot_m, plot_epsilon_droot_rootd, plot_epsilon_droot_halfd , plot_epsilon_dlinear_m, plot_epsilon_dlinear_rootd, plot_epsilon_dlinear_halfd,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 2)

```


```{r, echo = F, eval = T}

x_l <-   xlab("Log Dimensions")

res$"m/k" <- res$m/res$k
res$"b Values" <- as.factor(res$b)

p_type <- geom_point( alpha = 0.3)
l_n <- labs(color='b') 
#plot 1
plot_epsilon_droot_m <- ggplot(res, aes(x = log(d), y = epsilon_droot_m, color = as.factor(b) )) + p_type +  x_l + ylab("root m epsilon")  + expand_limits(y = 0)  + l_n 


#plot 2
plot_epsilon_droot_rootd <- ggplot(res, aes(x = log(d), y = epsilon_droot_rootd, color = as.factor(b))) + p_type  +  x_l + ylab("root root epsilon") + l_n

#plot 3
plot_epsilon_droot_halfd <- ggplot(res, aes(x = log(d), y = epsilon_droot_halfd, color = as.factor(b) )) + p_type  +  x_l + ylab("root halfed epsilon") + expand_limits(y = 0)+ l_n

#plot 4
plot_epsilon_dlinear_m <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_m, color = as.factor(b) )) + p_type  +  x_l + ylab("Linear m epsilon") + scale_y_continuous(limits = c(0,150))+ l_n

#plot 5
plot_epsilon_dlinear_rootd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_rootd, color =  as.factor(b) )) + p_type  +  x_l + ylab("Linear root epsilon") + scale_y_continuous(limits = c(0,150))+ l_n

#plot 6
plot_epsilon_dlinear_halfd <- ggplot(res, aes(x = log(d), y = epsilon_dlinear_halfd, color = as.factor(b) )) + p_type  +  x_l + ylab("Linear halfed epsilon") + scale_y_continuous(limits = c(0,150))+ l_n

ggarrange(plot_epsilon_droot_m, plot_epsilon_droot_rootd, plot_epsilon_droot_halfd , plot_epsilon_dlinear_m, plot_epsilon_dlinear_rootd, plot_epsilon_dlinear_halfd,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 2)
```

```{r, echo = F, eval = T}

x_l <-   xlab("Log Dimensions")

res$distinguishable
l_n <- labs(color='distin') 
#plot 1
plot_abs_deviation <- ggplot(res, aes(x = log(d), y = log(abs_deviation), color = as.factor(distinguishable))) + geom_point() +  x_l + ylab("log abs dev") + expand_limits(y = 0) + l_n

#plot 2
plot_squared_deviation <- ggplot(res, aes(x = log(d), y = log(squared_deviation), color = as.factor(distinguishable) )) + geom_point() +  x_l + ylab("log sqr dev")  + l_n

#plot 3
plot_max_normed_deviation <- ggplot(res, aes(x = log(d), y = log(max_normed_deviation), color = as.factor(distinguishable) )) + geom_point() +  x_l + ylab("log max normed dev") + expand_limits(y = 0) + l_n



ggarrange(plot_abs_deviation, plot_abs_deviation, plot_max_normed_deviation,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 1)
```

```{r, echo = F, eval = T}

x_l <-   xlab("Log Dimensions")

res$max_normed_deviation

#plot 1
plot_abs_deviation <- ggplot(res, aes(x = log(d), y = log(abs_deviation), color = log(m/k) )) + geom_point() +  x_l + ylab("log abs dev") + expand_limits(y = 0)

#plot 2
plot_squared_deviation <- ggplot(res, aes(x = log(d), y = log(squared_deviation), color = log(m/k) )) + geom_point() +  x_l + ylab("log sqr dev") 

#plot 3
plot_max_normed_deviation <- ggplot(res, aes(x = log(d), y = log(max_normed_deviation), color = log(m/k) )) + geom_point() +  x_l + ylab("log max normed dev") + expand_limits(y = 0)



ggarrange(plot_abs_deviation, plot_abs_deviation, plot_max_normed_deviation,
          labels = c("A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 1)
```